version: '3'
services:
    mono:
        build:
            context: ./
            dockerfile: ./mono.dockerfile
        env_file: ./.env
        volumes:    
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
            - '.:/root/lab7'
